// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDabpFe_IXf_QizfX-CNBbeHl7BqfEPYWI',
    appId: '1:1097707747641:web:7c8c2ca57b2363ddabd0e8',
    messagingSenderId: '1097707747641',
    projectId: 'steam-login-d0e95',
    authDomain: 'steam-login-d0e95.firebaseapp.com',
    storageBucket: 'steam-login-d0e95.firebasestorage.app',
    measurementId: 'G-DJP42HVQX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ-aJPjIhA0kP50R0a8SlSIhibOuiGh3E',
    appId: '1:1097707747641:android:3e2c81dd17145cf0abd0e8',
    messagingSenderId: '1097707747641',
    projectId: 'steam-login-d0e95',
    storageBucket: 'steam-login-d0e95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9D4VU81nCKnHo5xKxe5njPQCKe2M0LA4',
    appId: '1:1097707747641:ios:8d862e82e68725faabd0e8',
    messagingSenderId: '1097707747641',
    projectId: 'steam-login-d0e95',
    storageBucket: 'steam-login-d0e95.firebasestorage.app',
    iosBundleId: 'com.example.trial1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9D4VU81nCKnHo5xKxe5njPQCKe2M0LA4',
    appId: '1:1097707747641:ios:8d862e82e68725faabd0e8',
    messagingSenderId: '1097707747641',
    projectId: 'steam-login-d0e95',
    storageBucket: 'steam-login-d0e95.firebasestorage.app',
    iosBundleId: 'com.example.trial1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDabpFe_IXf_QizfX-CNBbeHl7BqfEPYWI',
    appId: '1:1097707747641:web:47709b4c2b4a0539abd0e8',
    messagingSenderId: '1097707747641',
    projectId: 'steam-login-d0e95',
    authDomain: 'steam-login-d0e95.firebaseapp.com',
    storageBucket: 'steam-login-d0e95.firebasestorage.app',
    measurementId: 'G-987P057RET',
  );
}
